### ISSUE TITLE
Segmental Fault when using Jemalloc with DTO

### ISSUE THREAD

**Issue by AsaMyth** [intel/DTO#3] opened 2023-09-13 08:21 UTC
Environment:
Debian10

Steps to reproduce:
1. build jemalloc
```shell
git clone git clone https://github.com/jemalloc/jemalloc.git
./autogen.sh
make -j
``` 
2. start test program with jemalloc and dto
```shell
 LD_PRELOAD=path-to-libjemalloc.so:./libdto.so.1.0 ./dto-test-wodto
Segmentation fault (core dumped)
```

From coredump, it appears that,
1. Jemalloc has a dependncy on libstdc++, so loader loads libstdc++ first.
2. libstdc++'s init routine calls malloc which is redirected to jemalloc
3. jemalloc calls memset
4. memset is redirecto to dto
5. init_dto calls dlsym, which calls malloc, and goes to jemalloc again
6.after that things become a mess....

There is  a temporary hack to comment out the explicit calling of init_dto to bypass the issue, but this doesn't looks to be a reasonable soultion.
The init_dto will be inexplicitly called due to the constructor attribute, while this is happening later the time.

```
@@ -1328,7 +1331,7 @@ void *memset(void *s1, int c, size_t n)
                /* Use internal implementation while the
                 * library is being initialized
                 */
-               if (init_dto() == DTO_INITIALIZING)
+               //if (init_dto() == DTO_INITIALIZING)
                        return dto_internal_memset(s1, c, n);
        }

```

**Comment by skuma24** [comment] 2023-09-19 19:15
Thanks for reporting the issue.
I will look into fixing it.


From: Asa Myth ***@***.***>
Sent: Wednesday, September 13, 2023 1:21 AM
To: intel/DTO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [intel/DTO] Segmental Fault when using Jemalloc with DTO (Issue #3)


Environment:
Debian10

Steps to reproduce:

  1.  build jemalloc

git clone git clone https://github.com/jemalloc/jemalloc.git

./autogen.sh

make -j

  1.  start test program with jemalloc and dto

 LD_PRELOAD=path-to-libjemalloc.so:./libdto.so.1.0 ./dto-test-wodto

Segmentation fault (core dumped)

From coredump, it appears that,

  1.  Jemallo has a dependncy on libstdc++, so loader will load libstdc++ first.
  2.  libstdc++'s init routine will call malloc which is redirected to jemaloc
  3.  jemalloc will call memset
  4.  memset is redirecto to dto
  5.  dto_init will call dlsym, which call malloc, and go jemalloc again
  6.  and from there on things become a mess....

There is a temporary hack to comment out the explicit calling of init_dto to bypass the issue, but this doesn't looks to be a reasonable soultion.

@@ -1328,7 +1331,7 @@ void *memset(void *s1, int c, size_t n)

                /* Use internal implementation while the

                 * library is being initialized

                 */

-               if (init_dto() == DTO_INITIALIZING)

+               //if (init_dto() == DTO_INITIALIZING)

                        return dto_internal_memset(s1, c, n);

        }

**Comment by skuma24** [comment] 2023-10-19 00:42
The issue is that jemalloc is trying to initialize itself and calling memmove which DTO intercepts. Now DTO calls init_dto which tries to subscribe to DSAs using accel-config APIs. It calls accfg_new() which calls calloc which goes to jemalloc again but jemalloc hasn't fully initialized yet and hence it segfaults. 

To avoid this issue, use DTO_WQ_LIST environment variable. This enables DTO to subscribe to DSAs without using accel-config (and hence without calling calloc).

**Comment by skuma24** [comment] 2024-02-27 00:05
I have pushed a proper fix for this issue so that DTO_WQ_LIST is no longer required as a workaround. This jemalloc scenario can work now even without DTO_WQ_LIST.

**Closed** 2024-03-12 13:41 UTC
